### ISSUE TITLE
some results don't make sense...

### ISSUE THREAD

**Issue by leeoniya** [willfarrell/csv-benchmarks#1]
hey @willfarrell 

i'm running some different (real world) benchmarks and having trouble replicating your results here.

for instance, this one strikes me as highly improbable. how is `10x10k` 2.3x slower than `100x10k`?

![image](https://github.com/willfarrell/csv-benchmarks/assets/43234/b716e601-e198-4464-bcfa-990c183efa82)`

**Comment by leeoniya** [comment]
below is what i'm seeing (Linux 6.4.12-arch1-1, AMD Ryzen Pro 5850, Node v20.5.1)

```
┌────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ 10x100000_slim.csv (7.6 MB, 10 cols x 100K rows)                                                                                                                                       │
├──────────────────┬────────┬─────────────────────────────────────────────────────────┬────────────────────────────────────┬────────┬────────────────────────────────────────────────────┤
│ Name             │ Rows/s │ Throughput (MiB/s)                                      │ RSS above 49 MiB baseline (MiB)    │ Types  │ Sample                                             │
├──────────────────┼────────┼─────────────────────────────────────────────────────────┼────────────────────────────────────┼────────┼────────────────────────────────────────────────────┤
│ PapaParse (file) │ 1.17M  │ ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 89.1 │ ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 536 │ string │ [["0x0","1x0","2x0","3x0","4x0","5x0","6x0","7x0", │
│ csv-rex (file)   │ 734K   │ ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 55.9                   │ ░░░░░░░░░░░░░░░░░░░░░░░░░░░ 475    │ string │ [["0x0","1x0","2x0","3x0","4x0","5x0","6x0","7x0", │
└──────────────────┴────────┴─────────────────────────────────────────────────────────┴────────────────────────────────────┴────────┴────────────────────────────────────────────────────┘
```

```
┌─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ 100x100000_slim.csv (84 MB, 100 cols x 100K rows)                                                                                                                                       │
├──────────────────┬────────┬────────────────────────────────────────────────────────┬──────────────────────────────────────┬────────┬────────────────────────────────────────────────────┤
│ Name             │ Rows/s │ Throughput (MiB/s)                                     │ RSS above 47 MiB baseline (MiB)      │ Types  │ Sample                                             │
├──────────────────┼────────┼────────────────────────────────────────────────────────┼──────────────────────────────────────┼────────┼────────────────────────────────────────────────────┤
│ PapaParse (file) │ 140K   │ ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 118 │ ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 2.35K │ string │ [["0x0","1x0","2x0","3x0","4x0","5x0","6x0","7x0", │
│ csv-rex (file)   │ 85.3K  │ ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 71.5                   │ ░░░░░░░░░░░░░░░░░░░░░░░░ 1.84K       │ string │ [["0x0","1x0","2x0","3x0","4x0","5x0","6x0","7x0", │
└──────────────────┴────────┴────────────────────────────────────────────────────────┴──────────────────────────────────────┴────────┴────────────────────────────────────────────────────┘
```

the code i'm using for each is:

```js
module.exports = {
  name: 'csv-rex (file)',
  repo: 'https://github.com/willfarrell/csv-rex',
  load: async () => {
    const { createReadStream } = await import('node:fs');
    const { pipejoin, streamToArray } = await import('@datastream/core');
    const { csvParseStream } = await import('@datastream/csv');

    return (csvStr, path) => new Promise(res => {
      const streams = [
        createReadStream(path),
        csvParseStream({ header: false }),
      ];

      const stream = pipejoin(streams);
      streamToArray(stream).then(res);
    });
  },
};
```

```js
const fs = require('fs');

module.exports = {
  name: 'PapaParse (file)',
  repo: 'https://github.com/mholt/PapaParse',
  load: async () => {
    const { default: Papa } = await import('papaparse');

    return (csvStr, path) => new Promise(res => {
      const file = fs.createReadStream(path);
      let rows = [];

      Papa.parse(file, {
        chunk: (result) => {
          rows.push(...result.data);
        },
        complete: (results, file) => {
          res(rows);
        }
      });
    });
  },
};
```

**Comment by leeoniya** [comment]
also, this code generates 11 and 101 columns :)

https://github.com/willfarrell/csv-benchmarks/blob/e25ce9b8726cf556c82d0ed98aefe65ff57afa6e/lib/generateCSV.js#L24-L27

**Comment by willfarrell** [comment]
Hey, I also found it highly improbable but was unsuccessful in finding out the root cause (oddly only for when there are no quotes). All packages use the same wrapper and papaparse is literally a one liner, it makes no sense why its results would look like that. It's a mystery I would love solved.

Your results are very interesting. In our real-world data we saw csv-rex out perform papaparse, with the added benefits of being esm and being <1.5kB (min+br) it was a no brainer to change over. Maybe it's time to revisit and update.

> this code generates 11 and 101 columns 

If you'd like to make a PR, i'd be happy to merge it in. Otherwise, I'll push an update next week.

PS Big fan of uPlot!

**Comment by leeoniya** [comment]
> If you'd like to make a PR, i'd be happy to merge it in. Otherwise, I'll push an update next week.

i was gonna submit a PR to include my own CSV parser, but found the scaffolding here a bit complex (especially with the requirement to streamify/pipe all the things).

i wrote my own benchmarking scaffold that accommodates both streaming and non-streaming parsers. i just added `csv-rex` to it here: https://github.com/leeoniya/uDSV/tree/main/bench (https://github.com/leeoniya/uDSV/commit/d91ff71ad0d420196c156e54bc9799e35154ae42) and will update the results tomorrow. in that commit i also added the synthetic datagen from your benchmark to mine, to be able to do apples-to-apples. would be interesting to compare notes.

> PS Big fan of uPlot!

thanks :)

**EDIT**: i re-ran and updated my benchmarks with csv-rex. unfortunately, i could not corroborate the claim that csv-rex is meaningfully faster than PapaParse...mostly it's in the same ballpark. i see that the CI is running ubuntu/node 18.17.1, but the perf gap between the benchmarks seems too large for that alone to explain the difference. i wonder what you get if you run mine locally :thinking:.
